Preserve data
Elisha-Tetteyfio/school-library pull request #6
Opened 2022-09-13 19:03 UTC by Elisha-Tetteyfio

In this milestone, myself and @henrycode460  refactored the methods to include methods to store data locally.
- Method to save data for `people`
- Method to save data for `books`
- Method to save data for `rentals`

2022-09-13 19:35 UTC, Nemwel-Boniface requested changes
## Hello @Elisha-Tetteyfio and @henrycode460       :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job working on your project so far :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 19:35 UTC, Nemwel-Boniface commented on create_person.rb
> +      @people << student_obj
- [ ] Great job saving and retrieving data. The application saves and works mostly as expected. The only issue comes when I already have some data in the "database" (.json) files on app start and I add some more data, the original data gets overwritten and now only the new data is present in the .json files. Kindly look into this.

[Screencast from 13-09-2022 10:10:37 ALASIRI.webm](https://user-images.githubusercontent.com/86318284/189990208-773ddf05-b7b1-498e-bea5-1a796f068e57.webm)

2022-09-14 09:54 UTC, Elisha-Tetteyfio commented
Thank you @Nemwel-Boniface , we will review that.

2022-09-14 10:11 UTC, m05e5 approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Elisha-Tetteyfio  🔥 

Good job on implementing the required changes. Well Done.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


Now you can merge this branch 🚀 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 10:33 UTC, merged